name: Docker Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk
      
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y wget unzip
        
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Android SDK
      run: |
        export ANDROID_SDK_ROOT=/opt/android-sdk
        mkdir -p ${ANDROID_SDK_ROOT}
        cd ${ANDROID_SDK_ROOT}
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip
        yes | cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        
    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=/opt/android-sdk
        export PATH=${PATH}:${ANDROID_SDK_ROOT}/platform-tools
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: docker-built-apk
        path: app/build/outputs/apk/debug/app-debug.apk
