name: Simple Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # First use Java 17 so sdkmanager runs correctly
    - name: Setup Java 17 for SDK tools
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
    
    # Then switch to Java 8 for Gradle build (AGP 4.x)
    - name: Switch to Java 8 for Gradle
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Build
      run: |
        # Verify gradle wrapper jar is valid; replace if needed
        if ! jar tf gradle/wrapper/gradle-wrapper.jar | grep -q GradleWrapperMain; then
          echo "gradle-wrapper.jar invalid or missing, redownloading..."
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v7.0.2/gradle/wrapper/gradle-wrapper.jar
        fi
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
